defaults: &defaults
  docker:
    - image: circleci/ruby:2.6.3-node
    - image: circleci/postgres:11
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Jest Tests
          command: npm test
  cypress:
    <<: *defaults
    steps:
      - checkout
      - run scripts/cypress.sh

workflows:
  version: 2
  build:
    jobs:
      - build
