defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/ruby:2.6.3-node-browsers
      environment:
        PGHOST: localhost
        PGUSER: quiz-us-server
        RAILS_ENV: test
    - image: circleci/postgres:11
      environment:
        POSTGRES_USER: quiz-us-server
        POSTGRES_DB: uiz-us-server_test
        POSTGRES_PASSWORD: ''
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Jest Tests
          command: npm test
      - run:
          name: cypress
          command: |
            git clone git@github.com:quiz-us/quiz-us-server.git
            cd quiz-us-server
            gem install bundler:2.0.2
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle exec rake db:create
            bundle exec rake db:schema:load
            echo "Database is set up!"

workflows:
  version: 2
  build:
    jobs:
      - build
