defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:10
  working_directory: ~/repo

ersion: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Jest Tests
          command: npm test
#   deploy_staging:
#     <<: *defaults
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#       - run: npx -p netlify-cli netlify deploy --dir=./build -e staging

workflows:
  version: 2
  build:
    jobs:
      - build
#   build_and_deploy_staging:
#     jobs:
#       - build
#       - deploy_staging:
#           requires:
#             - build
#           filters:
#             branches:
#               only: staging
